### ISSUE TITLE
Instance Scaling

### ISSUE THREAD

**Issue by smaun** [alexmx/AMXFontAutoScale#2]
I m unable to perform instance scaling, Is there any workaround other then your provided code snippet. While global scaling is doing great

**Comment by alexmx** [comment]
@smaun Thank you for reporting this. I will take a look and will come back with a fix shortly.

**Comment by alexmx** [comment]
@smaun Fixed in the latest release [1.0.2](https://github.com/alexmx/AMXFontAutoScale/releases/tag/v1.0.2).

**Comment by smaun** [comment]
Updated the POD to 1.0.2 but still having the same issue.
using like this,

override func viewDidLoad() {
    super.viewDidLoad()
    txtViewSetting.amx_autoScaleFont(forReferenceScreenSize: .size4Inch)
  }

**Comment by alexmx** [comment]
@smaun Are you applying instance scaling together with global one?
It will be easier for me if you provide me with more info. Thanks.

**Comment by alexmx** [comment]
@smaun My fault. I fixed the bug for UILabel only, from your sample I see that you use an UITextView. Will push a new release shorty.

**Comment by alexmx** [comment]
@smaun Should be fixed in the latest release [1.0.3](https://github.com/alexmx/AMXFontAutoScale/releases/tag/v1.0.3). 

Can you please confirm that it is working fine for you?

**Comment by smaun** [comment]
Working fine now cheers 👍
